### ISSUE TITLE
Mobile Facebook + IronSource Facebook cause build errors on iOS

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#341] opened 2020-11-12 03:35 UTC
## Request Type
This is a **Bug Report**.

## Describe the bug
When both Mobile Facebook and Ironsource Facebook plugins are added to the project, "cordova prepare" fails.
This is not just a warning message, if I try "cordova build", it fails with the same error.

If I remove either cordova-plugin-facebook4 or chadori-mobile-ironsource-facebook from the project, the problem goes away.
As you can see on the screenshot below, they are clearly conflicting..

![image](https://user-images.githubusercontent.com/36763350/98892865-52d1ca00-24f5-11eb-8667-eafbdde1dfed.png)

## Reproducible .c3p or .capx
https://www.dropbox.com/s/rxoi1vei8wkwr0y/IronSource_Debug7.c3p?dl=0

## Steps to Reproduce
Try building with Cordova CLI for iOS

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
218

## Additional Info

`admin@Mac-Admin i17 % cordova prepare
Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
Using cordova-fetch for cordova-ios@6.1.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: ../../../documents/myiosapps/i17/platforms/ios
	Package: com.sakkatstudio.brain
	Name: Brain Puzzle Ad test
iOS project created with cordova-ios@6.1.0
Plugin 'chadori-mobile-ironsource-facebook' found in config.xml... Migrating it to package.json
Plugin 'chadori-mobile-ironsource-chartboost' found in config.xml... Migrating it to package.json
Plugin 'chadori-mobile-ironsource-applovin' found in config.xml... Migrating it to package.json
Plugin 'chadori-mobile-ironsource-tapjoy' found in config.xml... Migrating it to package.json
Plugin 'chadori-mobile-ironsource-inmobi' found in config.xml... Migrating it to package.json
Plugin 'chadori-mobile-ironsource' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-facebook4' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'construct-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered plugin "chadori-mobile-ironsource-facebook". Adding it to the project
Installing "chadori-mobile-ironsource-facebook" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "chadori-mobile-ironsource-chartboost". Adding it to the project
Installing "chadori-mobile-ironsource-chartboost" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "chadori-mobile-ironsource-applovin". Adding it to the project
Installing "chadori-mobile-ironsource-applovin" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "chadori-mobile-ironsource-tapjoy". Adding it to the project
Installing "chadori-mobile-ironsource-tapjoy" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "chadori-mobile-ironsource-inmobi". Adding it to the project
Installing "chadori-mobile-ironsource-inmobi" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "chadori-mobile-ironsource". Adding it to the project
Installing "chadori-mobile-ironsource" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["IronSourceSDK", "TapjoySDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Discovered plugin "cordova-plugin-facebook4". Adding it to the project
Installing "cordova-plugin-facebook4" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-facebook4': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/admin/documents/myiosapps/i17/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
Failed to restore plugin "cordova-plugin-facebook4". You might need to try adding it again. Error: Error: pod: Command failed with exit code 1
Discovered plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Discovered plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Discovered plugin "construct-plugin-file". Adding it to the project
Installing "construct-plugin-file" for ios
Discovered plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Running manual pod update
Pod update failed
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit/Basics":
  In Podfile:
    FBSDKShareKit (= 5.15.0) was resolved to 5.15.0, which depends on
      FBSDKShareKit/Share (= 5.15.0) was resolved to 5.15.0, which depends on
        FBSDKCoreKit (~> 5.0) was resolved to 5.15.0, which depends on
          FBSDKCoreKit/Basics (= 5.15.0)

    IronSourceFacebookAdapter (= 4.3.21.0) was resolved to 4.3.21.0, which depends on
      FBAudienceNetwork (= 6.2.0) was resolved to 6.2.0, which depends on
        FBSDKCoreKit/Basics (>= 7.0.1)

CordovaError: Promise rejected with non-error: undefined
    at /usr/local/lib/node_modules/cordova/bin/cordova:30:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

`

**Comment by Chadori** [comment] 2020-11-12 11:49
Hi, thank you for reporting. I can reproduce the issue.
However, it seems to be a conflict with the recent update.

The Mobile IronSource Collection is using the latest IronSource iOS Facebook SDK, while the Mobile Facebook's iOS SDK wasn't updated. 
Unlike the IronSource collection, we are using an open-source library for the Facebook implementation, so we do not have control with its progress.

I think I may have a few solutions, I'll reply as soon as I confirm it.

**Comment by Chadori** [comment] 2020-12-14 20:43
Should now be resolved in https://github.com/Chadori/Construct-Master-Collection/issues/350.
Thank you.

**Closed as completed by Chadori** 2020-12-14 20:43 UTC
Labels: Bug, Mobile, IronSource

**Comment by baksarbed** [comment] 2022-02-01 09:59
I have the same error I changed IronSource to 7.0.1
% pod install                                                                 
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (6.4.1)
Installing FBSDKCoreKit (9.3.0)
Installing Google-Mobile-Ads-SDK (8.13.0)
Installing GoogleAppMeasurement (8.11.0)
Installing GoogleMobileAdsMediationFacebook (6.4.1.0)
Installing GoogleMobileAdsMediationIronSource (7.0.0.0)
Installing GoogleMobileAdsMediationTestSuite (2.0.0)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.7.0)
Installing IronSourceSDK (7.0.0.0)

[!] Error installing IronSourceSDK
[!] /usr/bin/curl -f -L -o /var/folders/xk/fvjqt06n2cv7bjcrxs83_7h40000gn/T/d20220201-41834-tpu643/file.zip https://dl.bintray.com/ironsource-mobile/ios-sdk/IronSource7.0.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 1 seconds. 2 retries left.
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 2 seconds. 1 retries left.
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502

**Comment by Chadori** [comment] 2022-02-01 14:16
No @baksarbed, it is clear that your errors are not the same. This is already long fixed with a different Construct 3 plugin replacement already been made long after.
Please refrain from commenting on old issues, if you need support please visit the [support channels](https://www.constructcollection.com/support). 

However, it does not look like you are even using our plugin, we do not use that kind of versioning.
